version: '3'

networks:
    app:

services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        container_name: app
        command: ./prepare.sh
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html
        networks:
            - app

    db:
        image: mysql:5.7
        container_name: db
        platform: linux/amd64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: cq_demo
            MYSQL_USER: cq_demo
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./docker/db:/var/lib/mysql
        networks:
            - app

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "3000:80"
        depends_on:
            - app
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app
